### ISSUE TITLE
Checking details for repo without remote host fails.

### ISSUE THREAD

**Issue by Nageswari-droid** [neel1996/gitconvex#99]
```
 {
  "id": "c28ebcec",
  "repoName": "Testing",
  "repoPath": "C:\\Users\\SVNPC\\Desktop\\js\\vanilla_js\\testing",
  "timestamp": "2020-11-16 13:58:53.0060524 +0530 IST m=+11849.732890401"
 }
]
2020/11/16 14:01:22 INFO: Collecting repo status information
2020/11/16 14:01:22 INFO: Collecting repo status information
2020/11/16 14:01:22 INFO: Available remotes in repo :
[0xc0003964c0]
2020/11/16 14:01:22 INFO: Available remotes in repo :
[0xc000065af0]
2020/11/16 14:01:22 INFO: Collecting repo status information
2020/11/16 14:01:22 INFO: Collecting repo status information
2020/11/16 14:01:22 INFO: Available remotes in repo :
[0xc0002d8560]
2020/11/16 14:01:22 INFO: Available remotes in repo :
[]
panic: runtime error: index out of range [0] with length 0

goroutine 37 [running]:
github.com/neel1996/gitconvex-server/git.RemoteData(0xc000109f50, 0xc00012c120)
        C:/Users/SVNPC/Desktop/js/gitconvex/git/git_remote_data.go:49 +0x1dc
created by github.com/neel1996/gitconvex-server/api.RepoStatus
        C:/Users/SVNPC/Desktop/js/gitconvex/api/repo_status.go:29 +0x255

```

**Comment by neel1996** [comment]
@Nageswari-droid Fix has been pushed to the repo. Retest and confirm

**Comment by Nageswari-droid** [comment]
```
 {
  "id": "c9562e82",
  "repoName": "test",
  "repoPath": "C:\\Users\\SVNPC\\Desktop\\js\\vanilla_js\\testing",
  "timestamp": "2020-11-17 00:14:41.153507 +0530 IST m=+96.079532101"
 }
]
2020/11/17 00:14:44 INFO: Available remotes in repo :
[0xc0002e63a0]
2020/11/17 00:14:44 INFO: Available remotes in repo :
[0xc000184240]
2020/11/17 00:14:44 INFO: Available Branch : heads/development
2020/11/17 00:14:44 INFO: Available Branch : heads/main
2020/11/17 00:14:44 INFO: Available Branch : remotes/github/main
2020/11/17 00:14:44 INFO: Available Branch : heads/master
2020/11/17 00:14:44 INFO: Available Branch : remotes/github/master
2020/11/17 00:14:44 INFO: Available Branch : remotes/github/under-development
2020/11/17 00:14:44 INFO: Total commits in the repo -> 2
2020/11/17 00:14:44 INFO: Total Tracked Files : 6
2020/11/17 00:14:44 INFO: Total commits in the repo -> 89
2020/11/17 00:14:44 INFO: Total Tracked Files : 63
2020/11/17 00:14:44 INFO: Collecting repo status information
2020/11/17 00:14:44 INFO: Available remotes in repo :
[]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x936582]

goroutine 120 [running]:
github.com/go-git/go-git/v5/plumbing.(*Reference).Name(...)
        C:/Users/SVNPC/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/reference.go:178
github.com/neel1996/gitconvex-server/git.GetBranchList(0xc000178570, 0xc000196120)
        C:/Users/SVNPC/Desktop/js/gitconvex/git/git_branch_list.go:32 +0x1c2
created by github.com/neel1996/gitconvex-server/api.RepoStatus
        C:/Users/SVNPC/Desktop/js/gitconvex/api/repo_status.go:59 +0x5c5

```

**Comment by neel1996** [comment]
@Nageswari-droid Fix pushed. Please check now.

**Comment by neel1996** [comment]
fixed in https://github.com/neel1996/gitconvex/commit/6042a9a4ce15daf81abeef7a5ffa7a7fc99abdba
